# Generated by Django 5.1.4 on 2024-12-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMSapp', '0002_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('course', models.CharField(max_length=200)),
                ('rollno', models.IntegerField()),
                ('age', models.IntegerField()),
            ],
        ),
    ]
